# Generated by Django 3.2.7 on 2021-09-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trabalhador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=400, verbose_name='Nome')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('profissao', models.CharField(max_length=200, verbose_name='profissão')),
                ('ano_contrato', models.IntegerField(verbose_name='Anos de contrato')),
                ('nuit', models.IntegerField(verbose_name='Nuit')),
                ('bi', models.CharField(max_length=50, verbose_name='N° de BI')),
                ('salario', models.IntegerField(verbose_name='salario')),
            ],
        ),
    ]
